apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ru3xct05y-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a56b83d870372cf13f19ec9dbf10c99b75b808b2@sha256:cc24dd4816e3d21c360efd6a6e656fbdad20e38f81140d446a9086e2eb4d3d4f
          name: container-image
